"""
Transit Platform — Intelligence Core Configuration
BUILD 3 Phase 1: Prototype configuration for GPS Validation.
"""

from typing import Tuple

# Coarse Geographic Sanity Guard (India Bounding Box)
COARSE_GEO_BOUNDS: Tuple[float, float, float, float] = (
    6.0,
    36.0,
    68.0,
    98.0,
)  # lat_min, lat_max, lon_min, lon_max

# Timestamps
ALLOWED_CLOCK_SKEW_SECONDS = 5.0
HISTORICAL_CLASSIFICATION_HORIZON_SECONDS = 900.0

# Physical Plausibility & Speeds
MAX_IMPOSSIBLE_SPEED_MPS = 50.0  # 180 km/h - Hard safety guard
SUSPICIOUS_SPEED_THRESHOLD_MPS = 33.3  # 120 km/h
MIN_PHYSICAL_DELTA_T_SECONDS = 2.0
MAX_PLAUSIBLE_ACCEL_MPS2 = 4.0

# Speed Consistency
SPEED_CONSISTENCY_MODERATE_MPS = 5.0
SPEED_CONSISTENCY_LARGE_MPS = 15.0
CONTINUITY_SPEED_SCALE = 10.0

# Confidence Component Initial Prototype Weights
WEIGHT_ACCURACY = 0.40
WEIGHT_SPEED = 0.25
WEIGHT_CONTINUITY = 0.20
WEIGHT_TIMESTAMP = 0.15

# Historical Score
HISTORICAL_TIMESTAMP_SCORE = 0.90

# Diagnostic Penalties (Multipliers)
CONFIDENCE_PENALTY_LOW_GPS = 0.80
CONFIDENCE_PENALTY_HIGH_SPEED = 0.60
CONFIDENCE_PENALTY_HIGH_ACCELERATION = 0.65
CONFIDENCE_PENALTY_SPEED_INCONSISTENCY = 0.75

# =================================================================
# PHASE 2: ROUTE MATCHING & DIRECTION
# =================================================================

# Adaptive Search Radius
SEARCH_RADIUS_BASE_M = 50.0
SEARCH_RADIUS_MAX_M = 300.0
SEARCH_RADIUS_ACCURACY_FACTOR = 1.5
SEARCH_RADIUS_SAFETY_MARGIN_M = 20.0

# Candidate Score Weights
ROUTE_WEIGHT_DISTANCE = 0.30
ROUTE_WEIGHT_HEADING = 0.15
ROUTE_WEIGHT_CONTINUITY = 0.25
ROUTE_WEIGHT_PROGRESSION = 0.20
ROUTE_WEIGHT_SPEED = 0.10

# Route Match Thresholds
MIN_ROUTE_MATCH_SCORE = 0.50
MIN_SCORE_MARGIN = 0.10

# Score Scales and Tolerances
ROUTE_DISTANCE_SCALE = 15.0  # Decays relative to max(accuracy, DISTANCE_SCALE)
CONTINUITY_PROGRESS_SCALE = 50.0  # Error scaling for expected progress delta

# Progression / Retrograde Handling
SMALL_RETROGRADE_TOLERANCE_M = 15.0
SMALL_RETROGRADE_SCORE = 0.70
MEANINGFUL_RETROGRADE_SCORE = 0.10
LEGITIMATE_REVERSAL_SCORE = 0.80

# Direction Engine
DIRECTION_CONFIRMATION_OBSERVATIONS = 3
DIRECTION_MIN_PROGRESS_DELTA = 15.0


# =================================================================
# PHASE 3: STOP PROGRESSION & DWELL DETECTION
# =================================================================

# Stop Progression Adaptive Tolerance
BASE_STOP_TOLERANCE_M = 30.0
STOP_ACCURACY_FACTOR = 1.2
MAX_STOP_TOLERANCE_M = 100.0

# Hysteresis Margins
STOP_AT_ENTER_MARGIN_M = 10.0
STOP_AT_EXIT_MARGIN_M = 10.0
STOP_PASS_MARGIN_M = 15.0
STOP_SPATIAL_PROXIMITY_M = 40.0

# Multi-Stop Gaps
MULTI_STOP_STRONG_MATCH_CONFIDENCE = 0.75

# Dwell Detection
STOP_SPEED_THRESHOLD_MPS = 0.55
STOP_DWELL_CONFIRM_SECONDS = 15.0
NON_STOP_DWELL_CONFIRM_SECONDS = 30.0
DWELL_EXIT_SPEED_THRESHOLD_MPS = 1.38

MOVEMENT_CONFIRMATION_OBSERVATIONS = 2
DWELL_EXIT_CONFIRMATION_OBSERVATIONS = 2
LARGE_PROGRESS_EXIT_M = 30.0


# =================================================================
# PHASE 4: TRIP INFERENCE & SCHEDULE ALIGNMENT
# =================================================================

# Windows
EARLY_DEPARTURE_ALLOWANCE_MIN = 30
LATE_DEPARTURE_ALLOWANCE_MIN = 120

# Thresholds
SUSPECTED_START_THRESHOLD = 50
ACTIVE_THRESHOLD = 70
RESET_THRESHOLD = 30
MAX_SUSPECTED_DURATION_MIN = 10

# Evidence weights and bounds
ORIGIN_PROXIMITY_M = 300.0
ROUTE_EVIDENCE_MIN_PROGRESS_DELTA_M = 50.0
ROUTE_MATCH_MAX_CONTRIBUTION = 25
STOP_PROGRESSION_MAX_CONTRIBUTION = 20

EVIDENCE_DECAY_PER_MINUTE = 5.0
DIRECTION_REQUIRED_FOR_ACTIVE = True

# Abandonment timeouts
ABANDONMENT_TELEMETRY_TIMEOUT_MIN = 15
ABANDONMENT_RECOVERY_GRACE_MIN = 5
UNEXPECTED_STOP_ABANDONMENT_MIN = 60

# Completion
COMPLETION_PROGRESS_THRESHOLD = 0.95


# =================================================================
# PHASE 5: TRACKER FUSION & CANONICAL BUS STATE
# =================================================================

# Weights
FUSION_WEIGHT_GPS = 0.30
FUSION_WEIGHT_RM = 0.25
FUSION_WEIGHT_ACC = 0.15
FUSION_WEIGHT_SPD = 0.10
FUSION_WEIGHT_CT = 0.10
FUSION_WEIGHT_SESS = 0.10

# Freshness Timeouts (seconds)
FUSION_LIVE_MAX_AGE_SECONDS = 90.0
FUSION_DEGRADED_MAX_AGE_SECONDS = 300.0
FUSION_STALE_MAX_AGE_SECONDS = 900.0

# Hysteresis and Source Switching
SOURCE_SWITCH_MARGIN = 0.15
SOURCE_SWITCH_CONFIRMATION_OBSERVATIONS = 2

# Disagreement Penalties and Thresholds
CANONICAL_MODERATE_DISAGREEMENT_PENALTY = 0.15
FUSION_DISAGREEMENT_SMALL_M = 20.0
FUSION_DISAGREEMENT_MODERATE_M = 100.0

# Confidence Mapping (To existing enum)
CANONICAL_CONFIDENCE_HIGH_THRESHOLD = 0.70
CANONICAL_CONFIDENCE_MEDIUM_THRESHOLD = 0.40
CANONICAL_CONFIDENCE_LOW_THRESHOLD = 0.00

# Recovery
MAX_PLAUSIBLE_RECOVERY_SPEED_MPS = 33.3
RECOVERY_CONFIRMATION_OBSERVATIONS = 2

# =================================================================
# PHASE 6: ETA ENGINE
# =================================================================

# Numerical Safeguards
ETA_MIN_SECONDS = 0
ETA_MAX_SECONDS = 28800
MIN_EFFECTIVE_SPEED_MPS = 1.0
MAX_EFFECTIVE_SPEED_MPS = 33.3

# Speed Model
ETA_EWMA_ALPHA = 0.35

# Historical Data
ETA_HISTORICAL_MIN_SAMPLES = 20

# Blending Weights
ETA_WEIGHT_LIVE_CURR = 0.85
ETA_WEIGHT_LIVE_HIST = 0.15
ETA_WEIGHT_DEGRADED_CURR = 0.40
ETA_WEIGHT_DEGRADED_HIST = 0.60

# Uncertainty Widening (seconds)
ETA_DEGRADED_UNCERTAINTY_MIN = 120.0
ETA_DWELL_NON_STOP_UNCERTAINTY_MIN = 300.0

# Base Canonical Confidence Numeric Mapping
ETA_CONFIDENCE_HIGH = 0.85
ETA_CONFIDENCE_MEDIUM = 0.60
ETA_CONFIDENCE_LOW = 0.30
