import os
import sys

# Ensure backend root is on sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Test Database Safety Guard:
# Fail closed immediately if DATABASE_URL points to the live database or any non-test database.
raw_db_url = os.environ.get("DATABASE_URL", "").strip()
if raw_db_url:
    from app.db.guard import extract_database_name, is_test_database
    db_name = extract_database_name(raw_db_url)
    if not is_test_database(db_name):
        raise RuntimeError(
            f"\n{'='*70}\n"
            f"FATAL TEST SAFETY ERROR: Test suite pointed at non-test database '{db_name}'.\n"
            f"Testing against live or non-test databases is STRICTLY FORBIDDEN!\n"
            f"All automated tests must target 'transit_platform_test'.\n"
            f"{'='*70}\n"
        )
else:
    # Default to isolated test database if unset
    os.environ["DATABASE_URL"] = "postgresql://transit:transit_dev_password@localhost:5432/transit_platform_test"

import pytest
from sqlalchemy import delete
from sqlalchemy.orm import Session

from app.db.guard import assert_testing_database
from app.db.database import engine
from app.db.seed import TRIP_PLANNED_ID
from app.models.enums import TripStatus
from app.models.state import BusCurrentState
from app.models.tracking import TrackingEvent, TrackingSession
from app.models.trip import Trip


@pytest.fixture(scope="session", autouse=True)
def guard_test_database_session():
    """
    Session-level safety fixture.
    Fails fast immediately if tests are executed against 'transit_platform'.
    """
    assert_testing_database(engine)


@pytest.fixture(autouse=True)
def reset_planned_trip_state():
    """
    Ensure TRIP_PLANNED_ID is in a deterministic state before every test.
    This prevents persistent local database state (from previous physical tests
    or out-of-order API tests) from causing test fixture contamination.
    """
    assert_testing_database(engine)

    with Session(engine) as session:
        # Delete dependent state generated by tracking tests/runs
        session.execute(delete(BusCurrentState).where(BusCurrentState.trip_id == TRIP_PLANNED_ID))
        session.execute(delete(TrackingEvent).where(TrackingEvent.trip_id == TRIP_PLANNED_ID))
        session.execute(delete(TrackingSession).where(TrackingSession.trip_id == TRIP_PLANNED_ID))

        # Reset trip status back to PLANNED
        trip = session.get(Trip, TRIP_PLANNED_ID)
        if trip:
            trip.status = TripStatus.PLANNED
            trip.actual_start_at = None
            trip.actual_end_at = None
            trip.start_source = None
            trip.end_source = None

        session.commit()
