import pytest
from sqlalchemy import delete
from sqlalchemy.orm import Session

from app.db.database import engine
from app.db.seed import TRIP_PLANNED_ID
from app.models.enums import TripStatus
from app.models.state import BusCurrentState
from app.models.tracking import TrackingEvent, TrackingSession
from app.models.trip import Trip


@pytest.fixture(autouse=True)
def reset_planned_trip_state():
    """
    Ensure TRIP_PLANNED_ID is in a deterministic state before every test.
    This prevents persistent local database state (from previous physical tests
    or out-of-order API tests) from causing test fixture contamination.
    """
    with Session(engine) as session:
        # Delete dependent state generated by tracking tests/runs
        session.execute(delete(BusCurrentState).where(BusCurrentState.trip_id == TRIP_PLANNED_ID))
        session.execute(delete(TrackingEvent).where(TrackingEvent.trip_id == TRIP_PLANNED_ID))
        session.execute(delete(TrackingSession).where(TrackingSession.trip_id == TRIP_PLANNED_ID))

        # Reset trip status back to PLANNED
        trip = session.get(Trip, TRIP_PLANNED_ID)
        if trip:
            trip.status = TripStatus.PLANNED
            trip.actual_start_at = None
            trip.actual_end_at = None
            trip.start_source = None
            trip.end_source = None

        session.commit()
