"""Add engine_contexts to BusCurrentState

Revision ID: 128fd62846cc
Revises: 8b5d3574a842
Create Date: 2026-08-29 20:23:52.745019
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "128fd62846cc"
down_revision: Union[str, None] = "8b5d3574a842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bus_current_state",
        sa.Column("engine_contexts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bus_current_state", "engine_contexts")
    # ### end Alembic commands ###
