"""add_fare_models

Revision ID: 6abc9ee3c967
Revises: e78cf56eeed2
Create Date: 2026-08-31 15:29:51.210018
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6abc9ee3c967'
down_revision: Union[str, None] = 'e78cf56eeed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fare_configurations_organization_id'), 'fare_configurations', ['organization_id'], unique=False)
    
    # Partial unique index to enforce exactly one active config per organization
    op.create_index(
        'uq_fare_configs_org_active',
        'fare_configurations',
        ['organization_id'],
        unique=True,
        postgresql_where=sa.text("is_active = true")
    )
    
    op.create_table('fare_slabs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fare_configuration_id', sa.UUID(), nullable=False),
    sa.Column('min_distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('min_distance_km >= 0', name='chk_fare_slabs_min_dist'),
    sa.CheckConstraint('fare_amount >= 0', name='chk_fare_slabs_fare_amount'),
    sa.CheckConstraint('max_distance_km IS NULL OR max_distance_km > min_distance_km', name='chk_fare_slabs_max_dist'),
    sa.ForeignKeyConstraint(['fare_configuration_id'], ['fare_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fare_slabs_fare_configuration_id'), 'fare_slabs', ['fare_configuration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fare_slabs_fare_configuration_id'), table_name='fare_slabs')
    op.drop_table('fare_slabs')
    op.drop_index('uq_fare_configs_org_active', table_name='fare_configurations')
    op.drop_index(op.f('ix_fare_configurations_organization_id'), table_name='fare_configurations')
    op.drop_table('fare_configurations')
    # ### end Alembic commands ###
