"""BUILD 3 - phase 7 crowding schema

Revision ID: 8b5d3574a842
Revises: 4fb7c61b0007
Create Date: 2026-08-29 04:08:19.707557
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b5d3574a842"
down_revision: Union[str, None] = "4fb7c61b0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_trips_id_org", "trips", ["id", "organization_id"])

    op.create_table(
        "crowding_reports",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=True),
        sa.Column(
            "crowding_state",
            sa.Enum("UNKNOWN", "LOW", "MODERATE", "HIGH", "FULL", name="crowdingstate"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("OPERATOR", "PASSENGER", "HISTORICAL", name="crowdingsource"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "trip_id"],
            ["trips.organization_id", "trips.id"],
            name="fk_crowding_org_trip",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "vehicle_id"],
            ["vehicles.organization_id", "vehicles.id"],
            name="fk_crowding_org_vehicle",
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_index(
        "idx_crowding_org_vehicle_observed",
        "crowding_reports",
        ["organization_id", "vehicle_id", "observed_at"],
        unique=False,
        postgresql_ops={"observed_at": "DESC"},
    )
    op.create_index(
        "idx_crowding_trip_observed",
        "crowding_reports",
        ["trip_id", "observed_at"],
        unique=False,
        postgresql_ops={"observed_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_crowding_trip_observed", table_name="crowding_reports")
    op.drop_index("idx_crowding_org_vehicle_observed", table_name="crowding_reports")
    op.drop_table("crowding_reports")

    op.drop_constraint("uq_trips_id_org", "trips", type_="unique")

    sa.Enum(name="crowdingstate").drop(op.get_bind())
    sa.Enum(name="crowdingsource").drop(op.get_bind())
    # ### end Alembic commands ###
