"""bus_current_state_phase_5_fields

Revision ID: 9b591141d0e9
Revises: 0001
Create Date: 2026-08-29 00:07:47.201440
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b591141d0e9"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bus_current_state", sa.Column("speed", sa.Float(), nullable=True))
    op.add_column("bus_current_state", sa.Column("heading", sa.Float(), nullable=True))
    op.add_column(
        "bus_current_state", sa.Column("dwell_state", sa.String(length=30), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bus_current_state", "dwell_state")
    op.drop_column("bus_current_state", "heading")
    op.drop_column("bus_current_state", "speed")
    # ### end Alembic commands ###
